apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kapilgohel1989/argocd.git
    targetRevision: "main"
    chart: my-firstchart
    path: helmChart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
